[package]
name = "asreadln"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.21.0"
clap = "4.5.30"
serde_json = "1.0.139"
webrtc-vad = "0.4.0"
whisper-rs = { version = "0.13.2", features = ["cuda"] }
